// <auto-generated />
using System;
using DrinkApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinkApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318234810_AddDrinkFkToOrder")]
    partial class AddDrinkFkToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrinkApi.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Sweetness")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Latte",
                            Price = 39.00m,
                            Sweetness = 5,
                            Type = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Green Tea",
                            Price = 29.00m,
                            Sweetness = 2,
                            Type = "Tea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mojito",
                            Price = 89.00m,
                            Sweetness = 7,
                            Type = "Cocktail"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Espresso",
                            Price = 29.00m,
                            Sweetness = 1,
                            Type = "Coffee"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cappuccino",
                            Price = 42.00m,
                            Sweetness = 4,
                            Type = "Coffee"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Americano",
                            Price = 35.00m,
                            Sweetness = 1,
                            Type = "Coffee"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mocha",
                            Price = 45.00m,
                            Sweetness = 7,
                            Type = "Coffee"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hot Chocolate",
                            Price = 38.00m,
                            Sweetness = 9,
                            Type = "Chocolate"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chai Latte",
                            Price = 42.00m,
                            Sweetness = 6,
                            Type = "Tea"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Matcha Latte",
                            Price = 48.00m,
                            Sweetness = 5,
                            Type = "Tea"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Earl Grey",
                            Price = 29.00m,
                            Sweetness = 2,
                            Type = "Tea"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Peppermint Tea",
                            Price = 29.00m,
                            Sweetness = 3,
                            Type = "Tea"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Orange Juice",
                            Price = 35.00m,
                            Sweetness = 8,
                            Type = "Juice"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Apple Juice",
                            Price = 35.00m,
                            Sweetness = 7,
                            Type = "Juice"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lemonade",
                            Price = 32.00m,
                            Sweetness = 8,
                            Type = "Juice"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Smoothie",
                            Price = 55.00m,
                            Sweetness = 7,
                            Type = "Smoothie"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Milkshake",
                            Price = 52.00m,
                            Sweetness = 10,
                            Type = "Milkshake"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Cola",
                            Price = 25.00m,
                            Sweetness = 9,
                            Type = "Soda"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sprite",
                            Price = 25.00m,
                            Sweetness = 8,
                            Type = "Soda"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Iced Tea",
                            Price = 32.00m,
                            Sweetness = 6,
                            Type = "Tea"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Margarita",
                            Price = 95.00m,
                            Sweetness = 6,
                            Type = "Cocktail"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Piña Colada",
                            Price = 99.00m,
                            Sweetness = 9,
                            Type = "Cocktail"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cosmopolitan",
                            Price = 92.00m,
                            Sweetness = 5,
                            Type = "Cocktail"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Long Island Iced Tea",
                            Price = 105.00m,
                            Sweetness = 7,
                            Type = "Cocktail"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Water",
                            Price = 15.00m,
                            Sweetness = 0,
                            Type = "Water"
                        });
                });

            modelBuilder.Entity("DrinkApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DrinkApi.Models.Order", b =>
                {
                    b.HasOne("DrinkApi.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drink");
                });
#pragma warning restore 612, 618
        }
    }
}
